common:
  speed:
    slowly: &SLOWLY
      speed: 0.15
      accel: 0.1
      timeout: 15.
    normally: &NORMALLY
      speed: 0.4
      accel: 0.3
      timeout: 3
    quickly: &QUICKLY
      speed: 0.6
      accel: 0.6
      timeout: 7.

  tolerance:
    small_tolerance: &SMALL_TOLERANCE
      tolerance_joints: [ 0.005, 0.008, 0.015, 0.1, 0.1, 0.1 ]
    normal_tolerance: &NORMAL_TOLERANCE
      tolerance_joints: [ 0.01, 0.010, 0.015, 0.3, 0.2, 0.15, 0.1 ]
    bigger_tolerance: &BIGGER_TOLERANCE
      tolerance_joints: [ 0.005, 0.010, 0.01, 0.3, 0.2, 0.2 ]
    max_tolerance: &MAX_TOLERANCE
      tolerance_joints: [ 0.03, 0.03, 0.03, 0.3, 0.3, 0.3 ]

  joint1:
    mechanical:
      down_position: &JOINT1_DOWN_POSITION
                       0.015
      up_position: &JOINT1_UP_POSITION
                     0.22
    home:
      zero_stone_position: &JOINT1_ZERO_STONE_POSITION
                             0.08
      one_stone_position: &JOINT1_ONE_STONE_POSITION
                            0.156
      two_stone_position: &JOINT1_TWO_STONE_POSITION
                            0.22
      three_stone_position: &JOINT1_THREE_STONE_POSITION
                              0.22

  joint2:
    mechanical:
      back_position: &JOINT2_BACK_POSITION
                       0.01
      get_ore_position: &JOINT2_GET_ORE_POSITION
                           0.1
      furthest_position: &JOINT2_FURTHEST_POSITION
                           0.2575
      exchange_position: &JOINT2_EXCHANGE_POSITION
                          0.07

  joint3:
    mechanical:
      left_position: &JOINT3_L_POSITION
                       0.28
      mid_position: &JOINT3_MID_POSITION
                      0.0001
      right_position: &JOINT3_R_POSITION
                        -0.275

  joint4:
    mechanical:
      left_position: &JOINT4_L_POSITION
                       1.00
      mid_position: &JOINT4_MID_POSITION
                      0.001
      right_position: &JOINT4_R_POSITION
                        -1.45
  joint5:
    mechanical:
      mid_position: &JOINT5_MID_POSITION
                      0.001
      left_90_position: &JOINT5_L90_POSITION
                          -1.54
      right_90_position: &JOINT5_R90_POSITION
                           1.59
  joint6:
    mechanical:
      mid_position: &JOINT6_MID_POSITION
                      0.001
      up_position: &JOINT6_UP_POSITION
                     -1.49
      down_position: &JOINT6_DOWN_POSITION
                       1.569
  joint7:
    mechanical:
      mid_position: &JOINT7_MID_POSITION
                      0.001
      left_90_position: &JOINT7_L90_POSITION
                          -1.59
      right_90_position: &JOINT7_R90_POSITION
                           1.49
  gimbal:
    side_pos: &SIDE_POS
      frame: gimbal_lifter
      position: [ 0.03 ,3, -0.02 ]
    island_pos: &ISLAND_POS
      frame: gimbal_lifter
      position: [ 2, 0.001, 0.001 ]
    ground_pos: &GROUND_POS
      frame: gimbal_lifter
      position: [ 2, 0.001, -0.8 ]

  gimbal_lifter:
    button_pos: &BUTTON_POS
      0.01
    mid_pos: &MID_POS
      0.1
    tallest_pos: &TALLEST_POS
      0.28

  gripper:
    open_gripper: &OPEN_GRIPPER
      pin: 0
      state: true
    close_gripper: &CLOSE_GRIPPER
      pin: 0
      state: false

  arm:
    home: &HOME_1
      joints: [ "VARIABLE", *JOINT2_BACK_POSITION, *JOINT3_MID_POSITION, *JOINT4_R_POSITION, *JOINT5_MID_POSITION, *JOINT6_UP_POSITION, *JOINT7_MID_POSITION ]
      common:
        <<: *NORMALLY
      tolerance:
        <<: *NORMAL_TOLERANCE


    reversal:
      velocity_stop: &VELOCITY_STOP
        mode: "VELOCITY"
        values: [ 0.,0.,0.,0.,0.,0. ]
      velocity_z_out: &VELOCITY_Z_OUT
        mode: "VELOCITY"
        values: [ 0.,0.,3.,0.,0.,0. ]
      velocity_z_out_store: &VELOCITY_Z_OUT_STORE
        mode: "VELOCITY"
        values: [ 0.,0.,0.2,0.,0.,0. ]
      velocity_z_in: &VELOCITY_Z_IN
        mode: "VELOCITY"
        values: [ 0.,0.,-1.2,0.,-0.01,0. ]
      velocity_z_in_quickly: &VELOCITY_Z_IN_QUICKLY
        mode: "VELOCITY"
        values: [ 0.,0.,-3.0,0.,-0.01,0. ]
      velocity_z_in_quickly_with_delay: &VELOCITY_Z_IN_QUICKLY_WITH_DELAY
        mode: "VELOCITY"
        values: [ 0.,0.,-3.0,0.,-0.01,0. ]
        delay: 0.3
      position_z_out: &POSITION_Z_OUT
        mode: "POSITION"
        values: [ 0.,0.,7.,0.,0.,0. ]
        delay: 0.2
      position_z_out_little: &POSITION_Z_OUT_LITTLE
        mode: "POSITION"
        values: [ 0.,0.,3.,0.,0.,0. ]
        delay: 0.4

    chassis_move:
      chassis_backward_30: &CHASSIS_BACKWARD_25
        frame: base_link
        position: [ -0.35,0. ]
        yaw: 0.0
        chassis_tolerance_position: 0.1
        chassis_tolerance_angular: 0.3
        common:
          timeout: 2.
      chassis_180: &CHASSIS_180
        frame: base_link
        position: [ 0., 0. ]
        yaw: 2.80
        chassis_tolerance_position: 0.1
        chassis_tolerance_angular: 0.2
        common:
          timeout: 2.

steps_list:
  ###################### SMALL_ISLAND #######################
  SMALL_ISLAND_DEMO:
    - step: "home pos"
      arm:
        joints: [ *JOINT1_ZERO_STONE_POSITION, *JOINT2_BACK_POSITION, *JOINT3_L_POSITION, *JOINT4_R_POSITION, *JOINT5_MID_POSITION, *JOINT6_UP_POSITION, *JOINT7_MID_POSITION ]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *NORMAL_TOLERANCE
#    - step: "open gripper"
#      gripper:
#        <<: *OPEN_GRIPPER
    - step: "ready to get ore"
      arm:
        joints: [ *JOINT1_ONE_STONE_POSITION, *JOINT2_BACK_POSITION, *JOINT3_L_POSITION, *JOINT4_R_POSITION, *JOINT5_L90_POSITION, *JOINT6_UP_POSITION, *JOINT7_R90_POSITION]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *NORMAL_TOLERANCE

  SMALL_ISLAND_DEMO0:
    - step: "move up ore"
      arm:
        joints: [ *JOINT1_TWO_STONE_POSITION, *JOINT2_BACK_POSITION, *JOINT3_L_POSITION, *JOINT4_R_POSITION, *JOINT5_L90_POSITION, *JOINT6_UP_POSITION, *JOINT7_R90_POSITION ]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *NORMAL_TOLERANCE
    - step: "reverse ore"
      arm:
        joints: [ *JOINT1_TWO_STONE_POSITION, *JOINT2_BACK_POSITION, *JOINT3_L_POSITION, *JOINT4_R_POSITION, *JOINT5_MID_POSITION, *JOINT6_UP_POSITION, *JOINT7_R90_POSITION ]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *NORMAL_TOLERANCE
    - step: "move ore back"
      arm:
        joints: [ *JOINT1_ONE_STONE_POSITION, *JOINT2_BACK_POSITION, *JOINT3_L_POSITION, *JOINT4_R_POSITION, *JOINT5_R90_POSITION, *JOINT6_UP_POSITION, *JOINT7_R90_POSITION ]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *NORMAL_TOLERANCE

  EXCHANGE_POS:
    - step: "gimbal look front"
      gimbal:
        <<: *ISLAND_POS
    - step: "move arm"
      arm:
        joints: [*JOINT1_TWO_STONE_POSITION, *JOINT2_EXCHANGE_POSITION, *JOINT3_L_POSITION, *JOINT4_MID_POSITION, *JOINT5_MID_POSITION, *JOINT6_UP_POSITION, *JOINT7_MID_POSITION]
        common:
          <<: *NORMALLY
        tolerance:
          <<: *NORMAL_TOLERANCE

  GIMBAL_FRONT:
    - step: "gimbal look front"
      gimbal:
        <<: *ISLAND_POS
  GIMBAL_LEFT:
    - step: "gimbal look left"
      gimbal:
        <<: *SIDE_POS
  ############ MID #############

  ############################ HOME ##########################
  HOME_ZERO_STONE:
    - step: "gimbal look side"
      gimbal:
        <<: *ISLAND_POS
    - step: "close gripper"
      gripper:
        <<: *CLOSE_GRIPPER
    - step: "home with no stone"
      arm:
        <<: *HOME_1
        variable: [ *JOINT1_ZERO_STONE_POSITION, 0, 0, 0, 0, 0 ]
  HOME_ONE_STONE:
    - step: "gimbal look side"
      gimbal:
        <<: *ISLAND_POS
    - step: "close gripper"
      gripper:
        <<: *CLOSE_GRIPPER
    - step: "home with one stone"
      arm:
        <<: *HOME_1
        variable: [ *JOINT1_ONE_STONE_POSITION, 0, 0, 0, 0, 0 ]
  HOME_TWO_STONE:
    - step: "gimbal look side"
      gimbal:
        <<: *ISLAND_POS
    - step: "close gripper"
      gripper:
        <<: *CLOSE_GRIPPER
    - step: "home with two stone"
      arm:
        <<: *HOME_1
        variable: [ *JOINT1_TWO_STONE_POSITION, 0, 0, 0, 0, 0 ]

  OPEN_GRIPPER:
    - step: "open gripper"
      gripper:
        <<: *OPEN_GRIPPER
  CLOSE_GRIPPER:
    - step: "close gripper"
      gripper:
        <<: *CLOSE_GRIPPER

  ########## EXCHANGE ############
  OLD_EXCHANGE_SPHERE:
    - step: "close to a sphere"
      arm:
        frame: exchanger
        xyz: [ -0.4, 0., -0.25 ]
        rpy: [ 0., 0., 0. ]
        rpy_rectify: [ 0.01,0.1,0.03 ]
        drift_dimensions: [ true, true, true, true, true, true ]
        tolerance_position: 0.1
        tolerance_orientation: 0.01
        spacial_shape: SPHERE
        radius: 0.5
        point_resolution: 0.5
        max_planning_times: 1
        common:
          <<: *QUICKLY

  EXCHANGE_DOWN:
    - step: "test new exchange"
      arm:
        frame: exchanger
        is_refer_planning_frame: true
        xyz: [ -0.3, 0.2, -0.2 ]
        rpy: [ 0., -1.5707963, 0. ]
        drift_dimensions: [ true, true, true, true, true, true ]
        tolerance_position: 0.01
        tolerance_orientation: 0.001
        spacial_shape: SPHERE
        radius: 0.3
        point_resolution: 0.5
        max_planning_times: 1
        common:
          <<: *NORMALLY

  TEST_ORI:
    - step: "ori test"
      arm:
        frame: exchanger
        rpy: [ 0., -1.5707963, 0. ]
        tolerance_orientation: 0.001

  TEST_ORI2:
    - step: "ori test2"
      arm:
        frame: exchanger
        rpy: [ 0., -1.5707963, 0. ]
        xyz: [ -0.3, 0.2, -0.2 ]
        tolerance_position: 0.01
        tolerance_orientation: 0.001

  EXCHANGE_ORI:
    - step: "test new exchange"
      arm:
        frame: exchanger
        is_refer_planning_frame: true
        rpy: [ 0., -1.5707963, 0. ]
        drift_dimensions: [ true, true, true, true, true, true ]
        tolerance_position: 0.01
        tolerance_orientation: 0.001
        spacial_shape: SPHERE
        radius: 0.5
        point_resolution: 0.5
        max_planning_times: 1
        common:
          <<: *NORMALLY
  EXCHANGE_STRAIGHT:
    - step: "test new exchange"
      arm:
        frame: exchanger
        is_refer_planning_frame: true
        xyz: [ -0.3, 0., 0. ]
        rpy: [ 0., 3.1415926, 0. ]
        drift_dimensions: [ true, true, true, true, true, true ]
        tolerance_position: 0.01
        tolerance_orientation: 0.001
        spacial_shape: SPHERE
        radius: 0.5
        point_resolution: 0.5
        max_planning_times: 1
        common:
          <<: *NORMALLY

  GTESTL:
    - step: "test"
      gimbal_lifter:
        target: *BUTTON_POS
  GTESTM:
    - step: "test"
      gimbal_lifter:
        target: *MID_POS
  GTESTH:
    - step: "test"
      gimbal_lifter:
        target: *TALLEST_POS


#    - step: "test new exchange"
#      arm:
#        frame: exchanger
#        is_refer_planning_frame: false
#        xyz: [ -0.2, 0., -0.18 ]
#        rpy: [ 0., 3.141592, 0. ]
#        drift_dimensions: [ true, true, true, true, false, true ]
#        tolerance_position: 0.01
#        tolerance_orientation: 0.01
#        spacial_shape: BASICS
#        basics_length: [ 0.1, 0.1, 0.1 ]
#        point_resolution: 0.6
#        max_planning_times: 50
#        common:
#          <<: *NORMALLY
